"""add restore fields to item

Revision ID: 4d748507b697
Revises: 293d4e4b24d5
Create Date: 2026-04-05 20:40:48.171898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d748507b697'
down_revision: Union[str, Sequence[str], None] = '293d4e4b24d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('item', sa.Column('restore_count', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'restore_count')
    op.drop_column('item', 'restored_at')
    # ### end Alembic commands ###
