"""add phone field to user

Revision ID: 71dbd5932dea
Revises: 648d77f4b62a
Create Date: 2026-03-22 07:17:05.957621

"""
from typing import Sequence, Union
import sqlmodel  # <--- เพิ่มบรรทัดนี้ครับ
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71dbd5932dea'
down_revision: Union[str, Sequence[str], None] = '648d77f4b62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
