apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-template.fullname" . }}-secrets
  labels:
    {{- include "fastapi-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
