{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-template.fullname" . }}-worker
  labels:
    {{- include "fastapi-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "fastapi-template.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "fastapi-template.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "fastapi-template.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "fastapi-template.fullname" . }}-config
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
