apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-configmap.yaml
  - app-deployment.yaml
  - app-hpa.yaml
  - app-ingress.yaml
  - app-networkpolicy.yaml
  - worker-deployment.yaml
  - outbox-dispatcher-deployment.yaml
  - cleanup-revoked-tokens-cronjob.yaml

secretGenerator:
  - name: fastapi-template-app-secrets
    behavior: replace
    literals:
      - SECURITY__SECRET_KEY=replace-with-a-long-random-secret

generatorOptions:
  disableNameSuffixHash: true
